export const C = {
  bg:       '#0d1117',
  surface1: '#161b22',
  surface2: '#1c2128',
  surface3: '#262c36',
  border:   '#30363d',
  text:     '#e6edf3',
  muted:    '#7a8899',
  accent:   '#c9a84c',
  green:    '#3fb950',
  red:      '#f85149',
  blue:     '#58a6ff',
  purple:   '#a78bfa',
  orange:   '#f97316',
};

export const S = {
  card: {
    backgroundColor: C.surface2,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
  },
  row: { flexDirection: 'row' as const, alignItems: 'center' as const },
  label: { fontSize: 11, textTransform: 'uppercase' as const, letterSpacing: 0.8, color: C.muted, fontWeight: '600' as const },
  title: { fontSize: 18, fontWeight: '700' as const, color: C.text },
  sub:   { fontSize: 13, color: C.muted },
  value: { fontSize: 22, fontWeight: '700' as const, color: C.text },
  btn: {
    backgroundColor: C.accent,
    borderRadius: 8,
    paddingVertical: 11,
    paddingHorizontal: 20,
    alignItems: 'center' as const,
  },
  btnText: { color: '#000', fontWeight: '700' as const, fontSize: 14 },
  btnGhost: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingVertical: 9,
    paddingHorizontal: 16,
    alignItems: 'center' as const,
  },
  btnGhostText: { color: C.muted, fontSize: 13 },
  input: {
    backgroundColor: C.surface3,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: C.text,
    fontSize: 14,
  },
  chip: {
    backgroundColor: C.surface3,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
};
